name: lecturecv-ex04
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab
  - numpy
  - matplotlib
  - k3d
  - scipy
  - imageio
  - pip
  - pip:
    - Pillow
    - trimesh
    # - pip:
    # - opencv-python==4.5.1.48
